title: æ¥šå¤±å¼“ğŸŒğŸ’»
description: è¿™æ˜¯æ¥è‡ªäºæˆ‘çš„ä¸ªäººåˆ†äº«ğŸ’¡ğŸ’¡ğŸ’¡
remote_theme: pmarsceill/just-the-docs
url: https://owl38383.github.io
color_scheme: dark


aux_links:
  ä»“åº“åœ°å€: https://github.com/owl38383
  ä¸ªäººä¸»é¡µ: https://mbad.top


#ä½¿ Aux é“¾æ¥åœ¨æ–°é€‰é¡¹å¡ä¸­æ‰“å¼€ã€‚é»˜è®¤ä¸ºå‡
aux_links_new_tab: true

#å¯¼èˆªé“¾æ¥çš„æ’åºé¡ºåº
# nav_sort: case_insensitive # é»˜è®¤ï¼Œç›¸å½“äºnil
nav_sort : case_sensitive #å¤§å†™å­—æ¯æ’åœ¨å°å†™å­—æ¯ä¹‹å‰
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html